// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PreviewCanvas from "./PreviewCanvas.res.mjs";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function BoolGridPreview(props) {
  let emptyColor = props.emptyColor;
  let filledColor = props.filledColor;
  let grid = props.grid;
  let canvasRef = React.useRef(null);
  React.useEffect(() => {
    let canvasElement = canvasRef.current;
    if (!(canvasElement == null)) {
      PreviewCanvas.drawBoolGrid(canvasElement, grid, filledColor, emptyColor);
    }
    
  }, [
    grid,
    filledColor,
    emptyColor
  ]);
  return JsxRuntime.jsx("canvas", {
    ref: Primitive_option.some(canvasRef),
    className: "w-full h-full block",
    style: {
      imageRendering: "pixelated"
    }
  });
}

let make = BoolGridPreview;

export {
  make,
}
/* react Not a pure module */
