// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.res.mjs";
import * as React from "react";
import * as Palette from "./Palette.res.mjs";
import * as PreviewCanvas from "./PreviewCanvas.res.mjs";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function BoolGridPreview(props) {
  let emptyColor = props.emptyColor;
  let filledColor = props.filledColor;
  let grid = props.grid;
  let canvasRef = React.useRef(null);
  let match = Theme.useTheme();
  React.useEffect(() => {
    let resolvedFilledColor = Stdlib_Option.flatMap(filledColor, Palette.resolveColor);
    let resolvedEmptyColor = Stdlib_Option.flatMap(emptyColor, Palette.resolveColor);
    let canvasElement = canvasRef.current;
    if (!(canvasElement == null)) {
      PreviewCanvas.drawBoolGrid(canvasElement, grid, resolvedFilledColor, resolvedEmptyColor);
    }
    
  }, [
    grid,
    filledColor,
    emptyColor,
    match[0]
  ]);
  return JsxRuntime.jsx("canvas", {
    ref: Primitive_option.some(canvasRef),
    className: "w-full h-full block object-contain ",
    style: {
      imageRendering: "pixelated"
    }
  });
}

let Palette$1;

let Theme$1;

let make = BoolGridPreview;

export {
  Palette$1 as Palette,
  Theme$1 as Theme,
  make,
}
/* Theme Not a pure module */
