// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

let options = [
  [
    "none",
    "None"
  ],
  [
    "overlay",
    "Shadow"
  ],
  [
    "color",
    "Color"
  ]
];

function buttonClass(isActive) {
  return "flex-1 text-xs font-medium px-1 py-1 rounded border transition-colors " + (
    isActive ? "bg-gray-900 text-white border-gray-900" : "bg-white text-gray-800 border-gray-200 hover:border-gray-400"
  );
}

function BrushOverlayControl(props) {
  let setOverlayMode = props.setOverlayMode;
  let overlayMode = props.overlayMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Brush Overlay",
        className: "font-medium"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map(options, param => {
          let label = param[1];
          let mode = param[0];
          return JsxRuntime.jsx("button", {
            children: label,
            className: buttonClass(overlayMode === mode),
            type: "button",
            onClick: param => setOverlayMode(param => mode)
          }, label);
        }),
        className: "grid grid-cols-3 gap-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = BrushOverlayControl;

export {
  options,
  buttonClass,
  make,
}
/* react/jsx-runtime Not a pure module */
