// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "./Styles.res.mjs";
import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function BrushOverlayControl(props) {
  let setOverlayMode = props.setOverlayMode;
  let overlayMode = props.overlayMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Brush Overlay",
        className: "font-bold text-sm"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map([
          [
            "none",
            "None"
          ],
          [
            "overlay",
            "Shadow"
          ],
          [
            "color",
            "Color"
          ]
        ], param => {
          let label = param[1];
          let mode = param[0];
          return JsxRuntime.jsx("button", {
            children: label,
            className: Styles.segmentButton(overlayMode === mode) + " py-1 first:rounded-l-xl last:rounded-r-xl",
            type: "button",
            onClick: param => setOverlayMode(param => mode)
          }, label);
        }),
        className: "grid grid-cols-3"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = BrushOverlayControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
