// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Switch from "./Switch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function BrushOverlayControl(props) {
  let setShowCursorOverlay = props.setShowCursorOverlay;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Brush Overlay",
        className: "flex flex-row font-medium"
      }),
      JsxRuntime.jsx(Switch.make, {
        checked: props.showCursorOverlay,
        onChange: v => setShowCursorOverlay(param => v)
      })
    ],
    className: "flex flex-row justify-between p-2 w-full"
  });
}

let make = BrushOverlayControl;

export {
  make,
}
/* Switch Not a pure module */
