// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BrushAndTileMaskSaveControl(props) {
  let handleDeleteSelectedTileMask = props.handleDeleteSelectedTileMask;
  let canDeleteSelectedTileMask = props.canDeleteSelectedTileMask;
  let setSelectedTileMaskIndex = props.setSelectedTileMaskIndex;
  let setSavedTileMasks = props.setSavedTileMasks;
  let setTileMask = props.setTileMask;
  let handleDeleteSelectedBrush = props.handleDeleteSelectedBrush;
  let canDeleteSelectedBrush = props.canDeleteSelectedBrush;
  let setSavedBrushes = props.setSavedBrushes;
  let setBrush = props.setBrush;
  let board = props.board;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Brush and Tile Masks",
        className: "flex flex-row items-center justify-between font-medium w-full"
      }),
      JsxRuntime.jsx("button", {
        children: "Add as Brush",
        className: "rounded px-2 py-1 text-sm font-medium bg-blue-500 text-white ",
        onClick: param => {
          let newBrush = board.map(row => row.map(cell => !(cell == null)));
          setSavedBrushes(v => v.concat([newBrush]));
          setBrush(param => newBrush);
        }
      }),
      JsxRuntime.jsx("button", {
        children: "Remove Brush",
        className: [
          "rounded px-2 py-1 text-sm font-medium",
          canDeleteSelectedBrush ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-500 cursor-not-allowed"
        ].join(" "),
        disabled: !canDeleteSelectedBrush,
        onClick: param => handleDeleteSelectedBrush()
      }),
      JsxRuntime.jsx("button", {
        children: "Add as Tile Mask",
        className: "rounded px-2 py-1 text-sm font-medium bg-blue-500 text-white",
        onClick: param => {
          let newTileMask = board.map(row => row.map(cell => !(cell == null)));
          setSavedTileMasks(prev => {
            let next = prev.concat([newTileMask]);
            setSelectedTileMaskIndex(param => next.length - 1 | 0);
            return next;
          });
          setTileMask(param => newTileMask);
        }
      }),
      JsxRuntime.jsx("button", {
        children: "Remove Tile Mask",
        className: [
          "rounded px-2 py-1 text-sm font-medium",
          canDeleteSelectedTileMask ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-500 cursor-not-allowed"
        ].join(" "),
        disabled: !canDeleteSelectedTileMask,
        onClick: param => handleDeleteSelectedTileMask()
      })
    ],
    className: "p-2 flex flex-col gap-2"
  });
}

let make = BrushAndTileMaskSaveControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
