// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function CanvasSizeControl(props) {
  let handleResizeSubmit = props.handleResizeSubmit;
  let canSubmitResize = props.canSubmitResize;
  let setResizeColsInput = props.setResizeColsInput;
  let setResizeRowsInput = props.setResizeRowsInput;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Canvas Size",
        className: ["flex flex-row items-center justify-between font-bold text-sm w-full"].join(" ")
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("input", {
                className: "border border-[var(--plain-300)] rounded px-2 py-1 text-sm flex-none w-16 ",
                value: props.resizeRowsInput,
                onChange: event => {
                  let value = event.target.value;
                  setResizeRowsInput(param => value);
                }
              }),
              JsxRuntime.jsx(Tb.TbX, {}),
              JsxRuntime.jsx("input", {
                className: "border border-[var(--plain-300)] rounded px-2 py-1 text-sm flex-none w-16 ",
                value: props.resizeColsInput,
                onChange: event => {
                  let value = event.target.value;
                  setResizeColsInput(param => value);
                }
              })
            ],
            className: "flex flex-row w-full gap-2 justify-between items-center"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("button", {
                children: "Save (Scale)",
                className: [
                  "rounded-lg px-1 py-1 text-xs font-medium flex-1",
                  canSubmitResize ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
                ].join(" "),
                disabled: !canSubmitResize,
                onClick: param => handleResizeSubmit("Crop")
              }),
              JsxRuntime.jsx("button", {
                children: "Save (Crop)",
                className: [
                  "rounded-lg px-1 py-1 text-xs font-medium flex-1",
                  canSubmitResize ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
                ].join(" "),
                disabled: !canSubmitResize,
                onClick: param => handleResizeSubmit("Scale")
              })
            ],
            className: "flex flex-row gap-2 w-full"
          })
        ],
        className: "flex flex-col gap-2"
      })
    ],
    className: " p-2 flex flex-col gap-2 w-full"
  });
}

let make = CanvasSizeControl;

export {
  make,
}
/* react-icons/tb Not a pure module */
