// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Initials from "./Initials.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function CanvasColorsControl(props) {
  let setViewportBackgroundColor = props.setViewportBackgroundColor;
  let setCanvasBackgroundColor = props.setCanvasBackgroundColor;
  let myColor = props.myColor;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Canvas Colors",
            className: "font-medium flex-1"
          }),
          JsxRuntime.jsx("button", {
            children: "Default",
            className: "flex flex-row items-center gap-1 text-xs font-medium ml-2",
            type: "button",
            onClick: param => {
              setCanvasBackgroundColor(param => Initials.canvasBackgroundColor);
              setViewportBackgroundColor(param => Initials.viewportBackgroundColor);
            }
          })
        ],
        className: "flex flex-row"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("button", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Background",
                className: "flex-1 text-left"
              }),
              JsxRuntime.jsx("div", {
                className: "w-6 h-6 border rounded",
                style: {
                  backgroundColor: props.canvasBackgroundColor
                }
              })
            ],
            className: "flex flex-row items-center gap-1 text-xs font-medium ",
            type: "button",
            onClick: param => setCanvasBackgroundColor(param => myColor)
          }),
          JsxRuntime.jsxs("button", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Viewport",
                className: "flex-1 text-left"
              }),
              JsxRuntime.jsx("div", {
                className: "w-6 h-6 border rounded",
                style: {
                  backgroundColor: props.viewportBackgroundColor
                }
              })
            ],
            className: "flex flex-row items-center gap-1 text-xs font-medium",
            type: "button",
            onClick: param => setViewportBackgroundColor(param => myColor)
          })
        ],
        className: "flex flex-col gap-1"
      })
    ],
    className: " p-2 flex flex-col gap-2 w-full"
  });
}

let make = CanvasColorsControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
