// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

let options = [
  [
    "none",
    "None"
  ],
  [
    "gridOverlay",
    "Grid Over"
  ],
  [
    "gridUnderlay",
    "Grid Under"
  ],
  [
    "checkeredOverlay",
    "Check Over"
  ],
  [
    "checkeredUnderlay",
    "Check Under"
  ]
];

function buttonClass(isActive) {
  return "flex-1 text-xs font-medium px-1 py-1 nth-[1]:rounded-t nth-[1]:col-span-2 nth-[4]:rounded-bl nth-[5]:rounded-br border transition-colors " + (
    isActive ? "bg-[color:var(--plain-900)] text-[color:var(--plain-white)] border-[color:var(--plain-900)]" : "bg-[color:var(--plain-white)] text-[color:var(--plain-800)] border-[color:var(--plain-200)] hover:border-[color:var(--plain-400)]"
  );
}

function CanvasGridControl(props) {
  let setGridMode = props.setGridMode;
  let gridMode = props.gridMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Canvas Guides",
        className: "font-medium"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map(options, param => {
          let label = param[1];
          let mode = param[0];
          return JsxRuntime.jsx("button", {
            children: label,
            className: buttonClass(gridMode === mode),
            type: "button",
            onClick: param => setGridMode(param => mode)
          }, label);
        }),
        className: "grid grid-cols-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = CanvasGridControl;

export {
  options,
  buttonClass,
  make,
}
/* react/jsx-runtime Not a pure module */
