// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "./Styles.res.mjs";
import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function CanvasGridControl(props) {
  let setGridMode = props.setGridMode;
  let gridMode = props.gridMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Canvas Guides",
        className: "font-bold text-sm "
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map([
          [
            "none",
            "None"
          ],
          [
            "gridOverlay",
            "Grid Over"
          ],
          [
            "gridUnderlay",
            "Grid Under"
          ],
          [
            "checkeredOverlay",
            "Check Over"
          ],
          [
            "checkeredUnderlay",
            "Check Under"
          ]
        ], param => {
          let label = param[1];
          let mode = param[0];
          return JsxRuntime.jsx("button", {
            children: label,
            className: Styles.segmentButton(gridMode === mode) + " py-1 nth-[1]:rounded-t-xl nth-[1]:col-span-2 nth-[4]:rounded-bl-xl nth-[5]:rounded-br-xl",
            type: "button",
            onClick: param => setGridMode(param => mode)
          }, label);
        }),
        className: "grid grid-cols-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = CanvasGridControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
