// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Initials from "./Initials.res.mjs";
import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as BoardPreview from "./BoardPreview.res.mjs";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function CanvasThumbnails(props) {
  let isMouseDown = props.isMouseDown;
  let handleSelectCanvas = props.handleSelectCanvas;
  let handleAddCanvas = props.handleAddCanvas;
  let handleDeleteCanvas = props.handleDeleteCanvas;
  let canDeleteCanvas = props.canDeleteCanvas;
  let currentCanvasId = props.currentCanvasId;
  let canvases = props.canvases;
  let findCanvasMetadata = id => Stdlib_Option.getOr(Belt_Array.getBy(canvases, canvas => canvas.id === id), {
    id: id,
    zoom: 1,
    pan: [
      0,
      0
    ],
    isDotMask: false,
    canvasBackgroundColor: Initials.canvasBackgroundColor
  });
  return JsxRuntime.jsxs("div", {
    children: [
      props.canvasBoards.map(param => {
        let id = param.id;
        findCanvasMetadata(id);
        let isSelectedCanvas = id === currentCanvasId;
        return JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("button", {
              children: JsxRuntime.jsx("div", {
                children: JsxRuntime.jsx(BoardPreview.make, {
                  board: param.board,
                  emptyColor: undefined,
                  isMouseDown: isMouseDown
                }),
                className: "h-16 w-16 rounded-xs overflow-hidden"
              }),
              className: [" w-fit h-fit block"].join(" "),
              onClick: param => handleSelectCanvas(id)
            }),
            isSelectedCanvas ? JsxRuntime.jsx("button", {
                children: JsxRuntime.jsx(Tb.TbTrash, {}),
                className: [
                  " w-4 h-4 leading-none text-sm font-medium absolute right-0 bottom-0 flex items-center justify-center",
                  canDeleteCanvas ? "bg-[var(--plain-700)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
                ].join(" "),
                disabled: !canDeleteCanvas,
                onClick: e => {
                  e.stopPropagation();
                  handleDeleteCanvas();
                }
              }) : null
          ],
          className: [
            "relative flex-shrink-0 border-2 w-fit h-fit",
            isSelectedCanvas ? "border-[var(--accent)]" : "border-[var(--plain-200)]"
          ].join(" ")
        }, id);
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbPlus, {}),
        className: "flex-shrink-0 h-16 w-16 border-2 border-dashed border-[var(--plain-300)] flex items-center justify-center text-3xl text-[var(--plain-400)]",
        onClick: param => handleAddCanvas()
      })
    ],
    className: "flex flex-row items-start gap-3 overflow-x-scroll p-2 pl-0"
  });
}

let make = CanvasThumbnails;

export {
  make,
}
/* BoardPreview Not a pure module */
