// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Switch from "./Switch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function CanvasGridControl(props) {
  let setShowGrid = props.setShowGrid;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Canvas Grid",
        className: "font-medium"
      }),
      JsxRuntime.jsx(Switch.make, {
        checked: props.showGrid,
        onChange: value => setShowGrid(param => value)
      })
    ],
    className: "flex flex-row items-center justify-between p-2 w-full"
  });
}

let make = CanvasGridControl;

export {
  make,
}
/* Switch Not a pure module */
