// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CanvasRendererJs from "./CanvasRenderer.js";

function create(prim) {
  return CanvasRendererJs.create(prim);
}

function dispose(prim) {
  CanvasRendererJs.dispose(prim);
}

function setSize(prim0, prim1, prim2, prim3) {
  CanvasRendererJs.setSize(prim0, prim1, prim2, prim3);
}

function updateBoard(prim0, prim1, prim2, prim3) {
  CanvasRendererJs.updateBoard(prim0, prim1, prim2, prim3);
}

function updateBrush(prim0, prim1, prim2, prim3) {
  CanvasRendererJs.updateBrush(prim0, prim1, prim2, prim3);
}

function updateTileMask(prim0, prim1) {
  CanvasRendererJs.updateTileMask(prim0, prim1);
}

function setOverlayOptions(prim0, prim1, prim2, prim3, prim4) {
  CanvasRendererJs.setOverlayOptions(prim0, prim1, prim2, prim3, prim4);
}

function setHover(prim0, prim1) {
  CanvasRendererJs.setHover(prim0, prim1);
}

function render(prim) {
  CanvasRendererJs.render(prim);
}

export {
  create,
  dispose,
  setSize,
  updateBoard,
  updateBrush,
  updateTileMask,
  setOverlayOptions,
  setHover,
  render,
}
/* ./CanvasRenderer.js Not a pure module */
