// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "./Styles.res.mjs";
import * as Belt_Array from "rescript/lib/es6/Belt_Array.js";
import * as ReactColorful from "react-colorful";
import * as JsxRuntime from "react/jsx-runtime";

function ColorControl(props) {
  let onStartColorPick = props.onStartColorPick;
  let isPickingColor = props.isPickingColor;
  let hoveredPickColor = props.hoveredPickColor;
  let setMyColor = props.setMyColor;
  let setBrushMode = props.setBrushMode;
  let brushMode = props.brushMode;
  let previewColor = hoveredPickColor !== undefined ? hoveredPickColor : props.canvasBackgroundColor;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: Belt_Array.map([
              [
                "Color",
                "Color"
              ],
              [
                "Erase",
                "Erase"
              ]
            ], param => {
              let label = param[1];
              let mode = param[0];
              return JsxRuntime.jsx("button", {
                children: label,
                className: Styles.segmentButton(brushMode === mode) + " py-1 px-3 first:rounded-l-xl last:rounded-r-xl",
                type: "button",
                onClick: param => setBrushMode(param => mode)
              }, label);
            }),
            className: "flex flex-row"
          }),
          JsxRuntime.jsx("button", {
            children: "Pick",
            className: [
              isPickingColor ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-900)]",
              "px-3 font-medium rounded-xl ml-2 text-xs"
            ].join(" "),
            onClick: param => onStartColorPick()
          })
        ],
        className: "flex flex-row justify-center"
      }),
      isPickingColor ? JsxRuntime.jsx("div", {
          className: "w-full h-[200px] border border-[var(--plain-300)]",
          style: {
            backgroundColor: previewColor
          }
        }) : JsxRuntime.jsx(ReactColorful.HexColorPicker, {
          color: props.myColor,
          onChange: newColor => setMyColor(param => newColor),
          style: {
            width: "96%"
          }
        })
    ],
    className: "relative flex flex-col gap-2 w-full overflow-x-visible items-center flex-none"
  });
}

let make = ColorControl;

export {
  make,
}
/* react-colorful Not a pure module */
