// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactColorful from "react-colorful";
import * as JsxRuntime from "react/jsx-runtime";

function ColorControl(props) {
  let setMyColor = props.setMyColor;
  let setBrushMode = props.setBrushMode;
  let brushMode = props.brushMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Color",
            className: [
              brushMode === "Color" ? " bg-blue-500 text-white" : "bg-gray-200",
              "px-2 font-medium rounded"
            ].join(" "),
            onClick: param => setBrushMode(param => "Color")
          }),
          JsxRuntime.jsx("button", {
            children: "Erase",
            className: [
              brushMode === "Erase" ? " bg-blue-500 text-white" : "bg-gray-200",
              "px-2 font-medium rounded"
            ].join(" "),
            onClick: param => setBrushMode(param => "Erase")
          })
        ],
        className: "flex flex-row gap-2 justify-center"
      }),
      JsxRuntime.jsx(ReactColorful.HexColorPicker, {
        color: props.myColor,
        onChange: newColor => setMyColor(param => newColor),
        style: {
          width: "96%"
        }
      })
    ],
    className: "relative flex flex-col gap-2 w-full overflow-x-visible items-center flex-none"
  });
}

let make = ColorControl;

export {
  make,
}
/* react-colorful Not a pure module */
