// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactColorful from "react-colorful";
import * as JsxRuntime from "react/jsx-runtime";

function ColorControl(props) {
  let onStartColorPick = props.onStartColorPick;
  let isPickingColor = props.isPickingColor;
  let hoveredPickColor = props.hoveredPickColor;
  let setMyColor = props.setMyColor;
  let setBrushMode = props.setBrushMode;
  let brushMode = props.brushMode;
  let previewColor = hoveredPickColor !== undefined ? hoveredPickColor : props.canvasBackgroundColor;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Color",
            className: [
              brushMode === "Color" ? "bg-[color:var(--accent)] text-[color:var(--plain-white)]" : "bg-[color:var(--plain-200)] text-[color:var(--plain-900)]",
              "px-2 font-medium rounded-l"
            ].join(" "),
            onClick: param => setBrushMode(param => "Color")
          }),
          JsxRuntime.jsx("button", {
            children: "Erase",
            className: [
              brushMode === "Erase" ? "bg-[color:var(--accent)] text-[color:var(--plain-white)]" : "bg-[color:var(--plain-200)] text-[color:var(--plain-900)]",
              "px-2 font-medium rounded-r"
            ].join(" "),
            onClick: param => setBrushMode(param => "Erase")
          }),
          JsxRuntime.jsx("button", {
            children: "Pick",
            className: [
              isPickingColor ? "bg-[color:var(--accent)] text-[color:var(--plain-white)]" : "bg-[color:var(--plain-200)] text-[color:var(--plain-900)]",
              "px-2 font-medium rounded ml-2"
            ].join(" "),
            onClick: param => onStartColorPick()
          })
        ],
        className: "flex flex-row justify-center"
      }),
      isPickingColor ? JsxRuntime.jsx("div", {
          className: "w-full h-[200px] border border-[color:var(--plain-300)]",
          style: {
            backgroundColor: previewColor
          }
        }) : JsxRuntime.jsx(ReactColorful.HexColorPicker, {
          color: props.myColor,
          onChange: newColor => setMyColor(param => newColor),
          style: {
            width: "96%"
          }
        })
    ],
    className: "relative flex flex-col gap-2 w-full overflow-x-visible items-center flex-none"
  });
}

let make = ColorControl;

export {
  make,
}
/* react-colorful Not a pure module */
