// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Switch from "./Switch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function DotModeControl(props) {
  let setCanvasDotMask = props.setCanvasDotMask;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Dot Mode",
        className: "font-medium"
      }),
      JsxRuntime.jsx(Switch.make, {
        checked: props.isDotMask,
        onChange: value => setCanvasDotMask(param => value)
      })
    ],
    className: "flex flex-row items-center justify-between p-2 w-full"
  });
}

let make = DotModeControl;

export {
  make,
}
/* Switch Not a pure module */
