// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ExportControl(props) {
  let onExport = props.onExport;
  let canExport = props.canExport;
  let setIncludeExportDotMask = props.setIncludeExportDotMask;
  let setIncludeExportBackground = props.setIncludeExportBackground;
  let setExportScaleInput = props.setExportScaleInput;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("span", {
        children: "Export PNG",
        className: "font-medium"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("label", {
            children: [
              JsxRuntime.jsx("span", {
                children: "Scale",
                className: "text-xs uppercase tracking-wide text-[var(--plain-500)]"
              }),
              JsxRuntime.jsx("input", {
                className: "border border-[var(--plain-300)]  rounded px-2 py-1 text-sm w-16",
                min: "1",
                step: 1.0,
                type: "number",
                value: props.exportScaleInput,
                onChange: event => {
                  let value = event.target.value;
                  setExportScaleInput(param => value);
                }
              })
            ],
            className: "flex flex-col gap-1 text-sm"
          }),
          JsxRuntime.jsx("button", {
            children: "Export",
            className: [
              "rounded-xl px-2 py-1 text-sm font-medium flex-1 h-fit",
              canExport ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
            ].join(" "),
            disabled: !canExport,
            onClick: param => onExport()
          })
        ],
        className: "flex flex-row  gap-2 items-end"
      }),
      JsxRuntime.jsxs("label", {
        children: [
          JsxRuntime.jsx("input", {
            checked: props.includeExportBackground,
            type: "checkbox",
            onChange: event => {
              let checked = event.target.checked;
              setIncludeExportBackground(param => checked);
            }
          }),
          JsxRuntime.jsx("span", {
            children: "Include Background"
          })
        ],
        className: "flex flex-row items-center gap-2 text-sm"
      }),
      JsxRuntime.jsxs("label", {
        children: [
          JsxRuntime.jsx("input", {
            checked: props.includeExportDotMask,
            type: "checkbox",
            onChange: event => {
              let checked = event.target.checked;
              setIncludeExportDotMask(param => checked);
            }
          }),
          JsxRuntime.jsx("span", {
            children: "Apply Dot Mask"
          })
        ],
        className: "flex flex-row items-center gap-2 text-sm"
      })
    ],
    className: " p-2 flex flex-col gap-2 w-full"
  });
}

let make = ExportControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
