// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HistoryControl(props) {
  let onRedo = props.onRedo;
  let onUndo = props.onUndo;
  let canRedo = props.canRedo;
  let canUndo = props.canUndo;
  let buttonClass = enabled => "flex-1 rounded px-2 py-1 text-xs font-medium flex items-center justify-center " + (
    enabled ? "bg-[color:var(--plain-200)] text-[color:var(--plain-900)]" : "bg-[color:var(--plain-100)] text-[color:var(--plain-400)] cursor-not-allowed"
  );
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "History",
            className: "font-medium"
          }),
          JsxRuntime.jsx("span", {
            children: "Cmd+Z / Cmd+Shift+Z",
            className: "text-xs text-[color:var(--plain-500)] font-mono"
          })
        ],
        className: "flex flex-row items-center justify-between"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Undo",
            className: buttonClass(canUndo),
            disabled: !canUndo,
            onClick: param => {
              if (canUndo) {
                return onUndo();
              }
              
            }
          }),
          JsxRuntime.jsx("button", {
            children: "Redo",
            className: buttonClass(canRedo),
            disabled: !canRedo,
            onClick: param => {
              if (canRedo) {
                return onRedo();
              }
              
            }
          })
        ],
        className: "flex flex-row gap-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = HistoryControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
