// Generated by ReScript, PLEASE EDIT WITH CARE


let EyeClosed = {};

let Eye = {};

let Slash = {};

let CircleSlash = {};

let X = {};

let Check = {};

let Plus = {};

let Minus = {};

let Trash = {};

let Pin = {};

let Archive = {};

let ArchiveOff = {};

let CornerDownRight = {};

let DragDrop = {};

let SquarePlus = {};

let ChevronDown = {};

let ChevronUp = {};

let ChevronRight = {};

let ChevronLeft = {};

let ArrowLeft = {};

let ArrowRight = {};

let Play = {};

let Pause = {};

let Stop = {};

let Stash = {};

let Inbox = {};

let Bookmark = {};

let Exclamation = {};

let Question = {};

let Future = {};

let Clock = {};

let Hand = {};

let Star = {};

let Hourglass = {};

let Sun = {};

let Moon = {};

export {
  EyeClosed,
  Eye,
  Slash,
  CircleSlash,
  X,
  Check,
  Plus,
  Minus,
  Trash,
  Pin,
  Archive,
  ArchiveOff,
  CornerDownRight,
  DragDrop,
  SquarePlus,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  Play,
  Pause,
  Stop,
  Stash,
  Inbox,
  Bookmark,
  Exclamation,
  Question,
  Future,
  Clock,
  Hand,
  Star,
  Hourglass,
  Sun,
  Moon,
}
/* No side effect */
