// Generated by ReScript, PLEASE EDIT WITH CARE


let canvasBackgroundColor = "#ffffff";

let viewportBackgroundColor = "#e5e7eb";

let myColor = "blue";

let zoom_factor = 1.1;

let maxZoomIn = 100;

let maxZoomOut = 0.01;

let silhouette = false;

export {
  canvasBackgroundColor,
  viewportBackgroundColor,
  myColor,
  zoom_factor,
  maxZoomIn,
  maxZoomOut,
  silhouette,
}
/* No side effect */
