// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemeColorsJs from "./themeColors.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function resolveThemeColor(prim) {
  return ThemeColorsJs.resolveThemeColor(prim);
}

function resolveColor(color) {
  return Primitive_option.fromNullable(ThemeColorsJs.resolveThemeColor(color));
}

let Thumbnail = {
  selectedFilled: "var(--plain-500, #575757)",
  selectedEmpty: "var(--plain-100, #E2E2E2)",
  unselectedFilled: "var(--plain-300, #9ca3af)",
  unselectedEmpty: "var(--plain-200, #e5e7eb)"
};

let gridLineDark = "rgba(0, 0, 0, 0.25)";

let gridLineLight = "rgba(255, 255, 255, 0.25)";

let checkeredPrimaryDark = "rgba(0, 0, 0, 0.15)";

let checkeredPrimaryLight = "rgba(255, 255, 255, 0.15)";

let checkeredSecondaryDark = "rgba(0, 0, 0, 0.00)";

let checkeredSecondaryLight = "rgba(255, 255, 255, 0.00)";

export {
  gridLineDark,
  gridLineLight,
  checkeredPrimaryDark,
  checkeredPrimaryLight,
  checkeredSecondaryDark,
  checkeredSecondaryLight,
  resolveThemeColor,
  resolveColor,
  Thumbnail,
}
/* ./themeColors.js Not a pure module */
