// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "rescript/lib/es6/Primitive_option.js";

function getColor() {
  return Stdlib_Option.getOr(Stdlib_Option.flatMap(Primitive_option.fromNullable(document.querySelector(".tan")), element => {
    let style = window.getComputedStyle(element);
    return Primitive_option.fromNullable(style.getPropertyValue("--plain-500"));
  }), "#dddddd");
}

console.log(getColor());

let Thumbnail = {
  selectedFilled: "#E7000B",
  selectedEmpty: "#FFCAC2",
  unselectedFilled: "#9ca3af",
  unselectedEmpty: "#e5e7eb"
};

let gridLineDark = "rgba(0, 0, 0, 0.25)";

let gridLineLight = "rgba(255, 255, 255, 0.25)";

let checkeredPrimaryDark = "rgba(0, 0, 0, 0.15)";

let checkeredPrimaryLight = "rgba(255, 255, 255, 0.15)";

let checkeredSecondaryDark = "rgba(0, 0, 0, 0.00)";

let checkeredSecondaryLight = "rgba(255, 255, 255, 0.00)";

export {
  gridLineDark,
  gridLineLight,
  checkeredPrimaryDark,
  checkeredPrimaryLight,
  checkeredSecondaryDark,
  checkeredSecondaryLight,
  getColor,
  Thumbnail,
}
/*  Not a pure module */
