// Generated by ReScript, PLEASE EDIT WITH CARE


let Thumbnail = {
  selectedFilled: "#E7000B",
  selectedEmpty: "#FFCAC2",
  unselectedFilled: "#9ca3af",
  unselectedEmpty: "#e5e7eb"
};

let gridLineDark = "rgba(0, 0, 0, 0.25)";

let gridLineLight = "rgba(255, 255, 255, 0.25)";

let checkeredPrimaryDark = "rgba(0, 0, 0, 0.15)";

let checkeredPrimaryLight = "rgba(255, 255, 255, 0.15)";

let checkeredSecondaryDark = "rgba(0, 0, 0, 0.00)";

let checkeredSecondaryLight = "rgba(255, 255, 255, 0.00)";

export {
  gridLineDark,
  gridLineLight,
  checkeredPrimaryDark,
  checkeredPrimaryLight,
  checkeredSecondaryDark,
  checkeredSecondaryLight,
  Thumbnail,
}
/* No side effect */
