// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PreviewCanvasRendererJs from "./PreviewCanvasRenderer.js";

function drawBoolGrid(prim0, prim1, prim2, prim3) {
  PreviewCanvasRendererJs.drawBoolGrid(prim0, prim1, prim2, prim3);
}

function drawBoard(prim0, prim1, prim2) {
  PreviewCanvasRendererJs.drawBoard(prim0, prim1, prim2);
}

export {
  drawBoolGrid,
  drawBoard,
}
/* ./PreviewCanvasRenderer.js Not a pure module */
