// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array2D from "./Array2D.res.mjs";

function prepareContext(canvasElement, width, height) {
  canvasElement.width = width;
  canvasElement.height = height;
  let ctx = canvasElement.getContext("2d");
  ctx.imageSmoothingEnabled = false;
  ctx.clearRect(0, 0, width, height);
  return ctx;
}

function drawBoolGrid(canvasElement, grid, trueColor, falseColor) {
  let match = Array2D.dims(grid);
  let width = match[1];
  let height = match[0];
  if (height === 0 || width === 0) {
    return;
  }
  let ctx = prepareContext(canvasElement, width, height);
  let lastColor = {
    contents: ""
  };
  grid.forEach((row, rowIndex) => {
    row.forEach((cell, colIndex) => {
      let color = cell ? trueColor : falseColor;
      if (color !== undefined) {
        if (color !== lastColor.contents) {
          ctx.fillStyle = color;
          lastColor.contents = color;
        }
        ctx.fillRect(colIndex, rowIndex, 1, 1);
        return;
      }
      
    });
  });
}

function drawBoard(canvasElement, board, emptyColor) {
  let match = Array2D.dims(board);
  let width = match[1];
  let height = match[0];
  if (height === 0 || width === 0) {
    return;
  }
  let ctx = prepareContext(canvasElement, width, height);
  let lastColor = {
    contents: ""
  };
  board.forEach((row, rowIndex) => {
    row.forEach((cell, colIndex) => {
      let color = (cell == null) ? emptyColor : cell;
      if (color !== undefined) {
        if (color !== lastColor.contents) {
          ctx.fillStyle = color;
          lastColor.contents = color;
        }
        ctx.fillRect(colIndex, rowIndex, 1, 1);
        return;
      }
      
    });
  });
}

export {
  prepareContext,
  drawBoolGrid,
  drawBoard,
}
/* Array2D Not a pure module */
