// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array2D from "./Array2D.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SavedTileMasksPanel(props) {
  let handleDeleteSelectedTileMask = props.handleDeleteSelectedTileMask;
  let canDeleteSelectedTileMask = props.canDeleteSelectedTileMask;
  let setSelectedTileMaskIndex = props.setSelectedTileMaskIndex;
  let selectedTileMaskIndex = props.selectedTileMaskIndex;
  let setSavedTileMasks = props.setSavedTileMasks;
  let setTileMask = props.setTileMask;
  let board = props.board;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "x",
            className: [
              "w-4 h-4 leading-none",
              canDeleteSelectedTileMask ? "bg-red-500 text-white" : "bg-gray-200 text-gray-500 cursor-not-allowed"
            ].join(" "),
            disabled: !canDeleteSelectedTileMask,
            onClick: param => handleDeleteSelectedTileMask()
          }),
          JsxRuntime.jsx("button", {
            children: "+",
            className: "bg-gray-200 w-4 h-4 leading-none",
            onClick: param => {
              let newTileMask = board.map(row => row.map(cell => !(cell == null)));
              setSavedTileMasks(prev => {
                let next = prev.concat([newTileMask]);
                setSelectedTileMaskIndex(param => next.length - 1 | 0);
                return next;
              });
              setTileMask(param => newTileMask);
            }
          })
        ]
      }),
      props.savedTileMasks.map((savedTileMask, savedTileMaskIndex) => {
        let match = Array2D.dims2D(savedTileMask);
        let selected = savedTileMaskIndex === selectedTileMaskIndex;
        return JsxRuntime.jsx("button", {
          children: JsxRuntime.jsx("div", {
            children: savedTileMask.map((line, i) => line.map((cell, j) => JsxRuntime.jsx("div", {
              className: [
                "w-full h-full ",
                selected ? (
                    cell ? "bg-orange-500" : "bg-orange-200"
                  ) : (
                    cell ? "bg-gray-400" : "bg-gray-200"
                  )
              ].join(" ")
            }, i.toString() + j.toString()))),
            className: [
              "h-8 w-8 rounded-xs overflow-hidden",
              selected ? "bg-orange-500 " : "bg-gray-400"
            ].join(" "),
            style: {
              display: "grid",
              gridTemplateColumns: "repeat(" + match[1].toString() + ", auto)",
              gridTemplateRows: "repeat(" + match[0].toString() + ", auto)"
            }
          }),
          onClick: param => {
            setSelectedTileMaskIndex(param => savedTileMaskIndex);
            setTileMask(param => savedTileMask);
          }
        }, savedTileMaskIndex.toString());
      })
    ],
    className: "flex flex-col gap-1 h-full overflow-y-scroll"
  });
}

let make = SavedTileMasksPanel;

export {
  make,
}
/* Array2D Not a pure module */
