// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BoolGridPreview from "./BoolGridPreview.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SavedTileMasksPanel(props) {
  let setSelectedTileMaskIndex = props.setSelectedTileMaskIndex;
  let selectedTileMaskIndex = props.selectedTileMaskIndex;
  let setTileMask = props.setTileMask;
  return JsxRuntime.jsx("div", {
    children: props.savedTileMasks.map((savedTileMask, savedTileMaskIndex) => {
      let selected = savedTileMaskIndex === selectedTileMaskIndex;
      let match = selected ? [
          "#f97316",
          "#fed7aa"
        ] : [
          "#9ca3af",
          "#e5e7eb"
        ];
      return JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(BoolGridPreview.make, {
            grid: savedTileMask,
            filledColor: match[0],
            emptyColor: match[1]
          }),
          className: [
            "h-8 w-8 rounded-xs overflow-hidden",
            selected ? "bg-orange-500 " : "bg-gray-400"
          ].join(" ")
        }),
        onClick: param => {
          setSelectedTileMaskIndex(param => savedTileMaskIndex);
          setTileMask(param => savedTileMask);
        }
      }, savedTileMaskIndex.toString());
    }),
    className: "flex flex-col gap-1 h-full overflow-y-scroll"
  });
}

let make = SavedTileMasksPanel;

export {
  make,
}
/* BoolGridPreview Not a pure module */
