// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Palette from "./Palette.res.mjs";
import * as Tb from "react-icons/tb";
import * as BoolGridPreview from "./BoolGridPreview.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SavedTileMasksPanel(props) {
  let canSaveTileMask = props.canSaveTileMask;
  let handleDeleteSelectedTileMask = props.handleDeleteSelectedTileMask;
  let canDeleteSelectedTileMask = props.canDeleteSelectedTileMask;
  let handleAddTileMask = props.handleAddTileMask;
  let setSelectedTileMaskId = props.setSelectedTileMaskId;
  let selectedTileMaskId = props.selectedTileMaskId;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Dither",
        className: "text-2xs font-bold"
      }),
      props.savedTileMasks.map(savedTileMask => {
        let selected = selectedTileMaskId !== undefined ? savedTileMask.id === selectedTileMaskId : false;
        let match = selected ? [
            Palette.Thumbnail.selectedFilled,
            Palette.Thumbnail.selectedEmpty
          ] : [
            Palette.Thumbnail.unselectedFilled,
            Palette.Thumbnail.unselectedEmpty
          ];
        return JsxRuntime.jsx("button", {
          children: JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx(BoolGridPreview.make, {
              grid: savedTileMask.mask,
              filledColor: match[0],
              emptyColor: match[1]
            }),
            className: [
              "h-8 w-8 rounded-xs overflow-hidden",
              selected ? "bg-orange-100 " : "bg-gray-100"
            ].join(" ")
          }),
          onClick: param => setSelectedTileMaskId(param => savedTileMask.id)
        }, savedTileMask.id);
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbPlus, {}),
        className: [
          "rounded p-1 h-6 w-6 text-sm font-medium",
          canSaveTileMask ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-500 cursor-not-allowed"
        ].join(" "),
        disabled: canSaveTileMask,
        onClick: param => handleAddTileMask()
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbTrash, {}),
        className: [
          "rounded p-1 h-6 w-6 text-sm font-medium",
          canDeleteSelectedTileMask ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-500 cursor-not-allowed"
        ].join(" "),
        disabled: !canDeleteSelectedTileMask,
        onClick: param => handleDeleteSelectedTileMask()
      })
    ],
    className: "flex flex-col gap-1 h-full overflow-y-scroll items-end"
  });
}

let Palette$1;

let make = SavedTileMasksPanel;

export {
  Palette$1 as Palette,
  make,
}
/* react-icons/tb Not a pure module */
