// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Array2D from "./Array2D.res.mjs";
import * as Palette from "./Palette.res.mjs";
import * as Tb from "react-icons/tb";
import * as BoolGridPreview from "./BoolGridPreview.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SavedBrushesPanel(props) {
  let canSaveBrush = props.canSaveBrush;
  let handleDeleteSelectedBrush = props.handleDeleteSelectedBrush;
  let canDeleteSelectedBrush = props.canDeleteSelectedBrush;
  let handleAddBrush = props.handleAddBrush;
  let setSelectedBrushId = props.setSelectedBrushId;
  let selectedBrushId = props.selectedBrushId;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Brush",
        className: "text-2xs font-bold"
      }),
      props.savedBrushes.map(savedBrushEntry => {
        let savedBrush = savedBrushEntry.brush;
        let match = Array2D.dims(savedBrush);
        let selected = selectedBrushId !== undefined ? savedBrushEntry.id === selectedBrushId : false;
        let match$1 = selected ? [
            Palette.Thumbnail.selectedFilled,
            Palette.Thumbnail.selectedEmpty
          ] : [
            Palette.Thumbnail.unselectedFilled,
            Palette.Thumbnail.unselectedEmpty
          ];
        return JsxRuntime.jsxs("button", {
          children: [
            JsxRuntime.jsx("div", {
              children: match[0].toString() + ":" + match[1].toString(),
              className: [" text-3xs font-bold w-4 text-center text-[var(--plain-black)]"].join(" "),
              style: {
                writingMode: "sideways-lr"
              }
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(BoolGridPreview.make, {
                grid: savedBrush,
                filledColor: match$1[0],
                emptyColor: match$1[1]
              }),
              className: [
                selected ? "bg-[var(--accent)]" : "bg-[var(--plain-400)]",
                "h-8 w-8 rounded-xs overflow-hidden"
              ].join(" ")
            })
          ],
          className: ["flex flex-row"].join(" "),
          onClick: param => setSelectedBrushId(param => savedBrushEntry.id)
        }, savedBrushEntry.id);
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbPlus, {}),
        className: [
          "rounded-lg h-8 w-8 text-lg font-medium flex items-center justify-center",
          canSaveBrush ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
        ].join(" "),
        disabled: !canSaveBrush,
        onClick: param => handleAddBrush()
      }),
      JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbTrash, {}),
        className: [
          "rounded-lg h-8 w-8 text-lg font-medium flex items-center justify-center",
          canDeleteSelectedBrush ? "bg-[var(--accent)] text-[var(--plain-white)]" : "bg-[var(--plain-200)] text-[var(--plain-500)] cursor-not-allowed"
        ].join(" "),
        disabled: !canDeleteSelectedBrush,
        onClick: param => handleDeleteSelectedBrush()
      })
    ],
    className: "flex flex-col gap-1 h-full overflow-y-scroll items-end"
  });
}

let Palette$1;

let make = SavedBrushesPanel;

export {
  Palette$1 as Palette,
  make,
}
/* Array2D Not a pure module */
