// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ScrollWheelControl(props) {
  let setScrollWheelMode = props.setScrollWheelMode;
  let scrollWheelMode = props.scrollWheelMode;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("span", {
          children: "Scroll Wheel",
          className: "font-medium"
        }),
        className: "flex flex-row items-center justify-between"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Zoom",
            className: "flex-1 px-2 py-1 text-xs font-medium rounded border " + (
              "zoom" === scrollWheelMode ? "bg-gray-900 text-white border-gray-900" : "bg-gray-100 text-gray-700 border-gray-200"
            ),
            onClick: param => setScrollWheelMode(param => "zoom")
          }),
          JsxRuntime.jsx("button", {
            children: "Pan",
            className: "flex-1 px-2 py-1 text-xs font-medium rounded border " + (
              "pan" === scrollWheelMode ? "bg-gray-900 text-white border-gray-900" : "bg-gray-100 text-gray-700 border-gray-200"
            ),
            onClick: param => setScrollWheelMode(param => "pan")
          })
        ],
        className: "flex flex-row gap-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = ScrollWheelControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
