// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Switch from "./Switch.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function SilhouetteControl(props) {
  let setIsSilhouette = props.setIsSilhouette;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Silhouette",
        className: "font-medium"
      }),
      JsxRuntime.jsx(Switch.make, {
        checked: props.isSilhouette,
        onChange: value => setIsSilhouette(param => value)
      })
    ],
    className: "flex flex-row items-center justify-between p-2 w-full"
  });
}

let make = SilhouetteControl;

export {
  make,
}
/* Switch Not a pure module */
