// Generated by ReScript, PLEASE EDIT WITH CARE


let canvases = "canvas-metadata-v1";

let savedBrushes = "saved-brushes";

let savedTileMasks = "saved-tile-masks";

let viewportBackgroundColor = "viewport-background-color";

let selectedBrushId = "selected-brush-id";

let selectedTileMaskId = "selected-tile-mask-id";

let selectedCanvasId = "selected-canvas-id";

let myColor = "my-color";

let brushMode = "brush-mode";

let brushOverlayMode = "brush-overlay-mode";

let gridMode = "grid-mode";

let silhouette = "canvas-silhouette";

let theme = "theme";

export {
  canvases,
  savedBrushes,
  savedTileMasks,
  viewportBackgroundColor,
  selectedBrushId,
  selectedTileMaskId,
  selectedCanvasId,
  myColor,
  brushMode,
  brushOverlayMode,
  gridMode,
  silhouette,
  theme,
}
/* No side effect */
