// Generated by ReScript, PLEASE EDIT WITH CARE


function segmentButton(isActive) {
  return "flex-1 text-xs font-medium   border transition-colors " + (
    isActive ? "bg-[var(--accent)] text-[var(--plain-white)] border-[var(--accent)]" : "bg-[var(--plain-white)] text-[var(--plain-800)] border-[var(--plain-200)] hover:border-[var(--plain-400)]"
  );
}

export {
  segmentButton,
}
/* No side effect */
