// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ThemeToggle(props) {
  let setTheme = props.setTheme;
  let theme = props.theme;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("span", {
          children: "Theme",
          className: "font-medium"
        }),
        className: "flex flex-row items-center justify-between"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Light",
            className: "flex-1 rounded px-2 py-1 text-xs font-medium border transition-colors " + (
              theme === "light" ? "bg-[var(--accent)] text-[var(--plain-white)] border-[var(--accent)]" : "bg-[var(--plain-200)] text-[var(--plain-900)] border-[var(--plain-300)]"
            ),
            onClick: param => setTheme(param => "light")
          }),
          JsxRuntime.jsx("button", {
            children: "Dark",
            className: "flex-1 rounded px-2 py-1 text-xs font-medium border transition-colors " + (
              theme === "dark" ? "bg-[var(--accent)] text-[var(--plain-white)] border-[var(--accent)]" : "bg-[var(--plain-200)] text-[var(--plain-900)] border-[var(--plain-300)]"
            ),
            onClick: param => setTheme(param => "dark")
          })
        ],
        className: "flex flex-row gap-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = ThemeToggle;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
