// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function ThemeToggle(props) {
  let myColor = props.myColor;
  let setCanvasBackgroundColor = props.setCanvasBackgroundColor;
  let setViewportBackgroundColor = props.setViewportBackgroundColor;
  let setTheme = props.setTheme;
  let buttonClass = " flex-none rounded w-7 h-7 flex flex-row items-center justify-center text-lg transition-colors bg-[var(--plain-200)] text-[var(--plain-black)]";
  let tmp;
  switch (props.theme) {
    case "dark" :
      tmp = JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbMoon, {}),
        className: buttonClass,
        onClick: param => {
          setTheme(param => "tan");
          setViewportBackgroundColor(param => "#FBE0C1");
        }
      });
      break;
    case "light" :
      tmp = JsxRuntime.jsx("button", {
        children: JsxRuntime.jsx(Tb.TbSun, {}),
        className: buttonClass,
        onClick: param => {
          setTheme(param => "dark");
          setViewportBackgroundColor(param => "#181818");
        }
      });
      break;
    case "tan" :
      tmp = JsxRuntime.jsx("button", {
        children: "🏝️",
        className: buttonClass,
        onClick: param => {
          setTheme(param => "pink");
          setViewportBackgroundColor(param => "#F4E6F0");
        }
      });
      break;
    case "pink" :
      tmp = JsxRuntime.jsx("button", {
        children: "🌸",
        className: buttonClass,
        onClick: param => {
          setTheme(param => "light");
          setViewportBackgroundColor(param => "#d8d8d8");
        }
      });
      break;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Background",
        className: "flex-1 text-sm font-bold"
      }),
      JsxRuntime.jsx("button", {
        className: "w-6 h-6 border rounded",
        style: {
          backgroundColor: props.canvasBackgroundColor
        },
        onClick: param => setCanvasBackgroundColor(param => myColor)
      }),
      tmp
    ],
    className: "p-2 flex flex-row gap-2 w-full items-center"
  });
}

let make = ThemeToggle;

export {
  make,
}
/* react-icons/tb Not a pure module */
