// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function ThemeToggle(props) {
  let myColor = props.myColor;
  let setCanvasBackgroundColor = props.setCanvasBackgroundColor;
  let setViewportBackgroundColor = props.setViewportBackgroundColor;
  let setTheme = props.setTheme;
  let buttonClass = "w-fit flex-none rounded p-1 text-lg transition-colors bg-[var(--plain-200)] text-[var(--plain-black)]";
  let tmp;
  tmp = props.theme === "dark" ? JsxRuntime.jsx("button", {
      children: JsxRuntime.jsx(Tb.TbMoon, {}),
      className: buttonClass,
      onClick: param => {
        setTheme(param => "light");
        setViewportBackgroundColor(param => "#d8d8d8");
      }
    }) : JsxRuntime.jsx("button", {
      children: JsxRuntime.jsx(Tb.TbSun, {}),
      className: buttonClass,
      onClick: param => {
        setTheme(param => "dark");
        setViewportBackgroundColor(param => "#181818");
      }
    });
  return JsxRuntime.jsxs("div", {
    children: [
      tmp,
      JsxRuntime.jsx("div", {
        children: "Background",
        className: "flex-1 text-right"
      }),
      JsxRuntime.jsx("button", {
        className: "w-6 h-6 border rounded",
        style: {
          backgroundColor: props.canvasBackgroundColor
        },
        onClick: param => setCanvasBackgroundColor(param => myColor)
      })
    ],
    className: "p-2 flex flex-row gap-2 w-full items-center"
  });
}

let make = ThemeToggle;

export {
  make,
}
/* react-icons/tb Not a pure module */
