// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as StorageKeys from "./StorageKeys.res.mjs";
import UseLocalStorageJs from "./useLocalStorage.js";

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs(prim0, prim1);
}

function useTheme() {
  let match = UseLocalStorageJs(StorageKeys.theme, "light");
  let theme = match[0];
  React.useEffect(() => {
    let match = theme === "dark" ? [
        "light",
        "dark"
      ] : [
        "dark",
        "light"
      ];
    document.documentElement.classList.remove(match[0]);
    document.documentElement.classList.add(match[1]);
  }, [theme]);
  return [
    theme,
    match[1]
  ];
}

export {
  useLocalStorage,
  useTheme,
}
/* react Not a pure module */
