// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as StorageKeys from "./StorageKeys.res.mjs";
import UseLocalStorageJs from "./useLocalStorage.js";

let allThemes = [
  "light",
  "dark",
  "tan",
  "pink"
];

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs(prim0, prim1);
}

function useTheme() {
  let match = UseLocalStorageJs(StorageKeys.theme, "light");
  let theme = match[0];
  React.useEffect(() => {
    allThemes.forEach(t => {
      document.documentElement.classList.remove(t);
    });
    document.documentElement.classList.add(theme);
  }, [theme]);
  return [
    theme,
    match[1]
  ];
}

export {
  allThemes,
  useLocalStorage,
  useTheme,
}
/* react Not a pure module */
