// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ZoomControl(props) {
  let onCenterCanvas = props.onCenterCanvas;
  let onZoomIn = props.onZoomIn;
  let onZoomReset = props.onZoomReset;
  let onZoomOut = props.onZoomOut;
  let zoomPercentString = (props.zoom * 100).toFixed(0);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Zoom",
            className: "font-medium"
          }),
          JsxRuntime.jsx("span", {
            children: zoomPercentString + "%",
            className: "text-sm font-mono"
          })
        ],
        className: "flex flex-row items-center justify-between"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "-",
            className: "flex-1 rounded px-2 py-1 text-sm font-medium bg-gray-200",
            onClick: param => onZoomOut()
          }),
          JsxRuntime.jsx("button", {
            children: "100%",
            className: "flex-1 rounded px-2 py-1 text-sm font-medium bg-gray-200",
            onClick: param => onZoomReset()
          }),
          JsxRuntime.jsx("button", {
            children: "+",
            className: "flex-1 rounded px-2 py-1 text-sm font-medium bg-gray-200",
            onClick: param => onZoomIn()
          })
        ],
        className: "flex flex-row gap-2"
      }),
      JsxRuntime.jsx("button", {
        children: "Center",
        className: "rounded px-2 py-1 text-sm font-medium bg-gray-200",
        onClick: param => onCenterCanvas()
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = ZoomControl;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
