// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function ZoomControl(props) {
  let fitCanvasToViewport = props.fitCanvasToViewport;
  let centerCanvas = props.centerCanvas;
  let zoomIn = props.zoomIn;
  let zoomOut = props.zoomOut;
  let zoomPercentString = props.zoomPercent.toFixed(0);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Zoom",
            className: "font-medium"
          }),
          JsxRuntime.jsx("span", {
            children: zoomPercentString + "%",
            className: "text-sm font-mono"
          })
        ],
        className: "flex flex-row items-center justify-between"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: JsxRuntime.jsx(Tb.TbMinus, {}),
            className: "flex-1 rounded px-2 py-1 text-sm font-medium bg-[color:var(--plain-200)] text-[color:var(--plain-900)] flex justify-center items-center",
            onClick: param => zoomOut()
          }),
          JsxRuntime.jsx("button", {
            children: JsxRuntime.jsx(Tb.TbPlus, {}),
            className: "flex-1 rounded px-2 py-1 text-sm font-medium bg-[color:var(--plain-200)] text-[color:var(--plain-900)] flex justify-center items-center",
            onClick: param => zoomIn()
          })
        ],
        className: "flex flex-row gap-2"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Fit",
            className: "flex-1 rounded px-2 py-1 text-xs font-medium bg-[color:var(--plain-200)] text-[color:var(--plain-900)]",
            onClick: param => fitCanvasToViewport()
          }),
          JsxRuntime.jsx("button", {
            children: "Center",
            className: "flex-1 rounded px-2 py-1 text-xs font-medium bg-[color:var(--plain-200)] text-[color:var(--plain-900)]",
            onClick: param => centerCanvas()
          })
        ],
        className: "flex flex-row gap-2"
      })
    ],
    className: "p-2 flex flex-col gap-2 w-full"
  });
}

let make = ZoomControl;

export {
  make,
}
/* react-icons/tb Not a pure module */
